"""
Shared types for the Proposer/Critic agent pair.

Strategy universe is deliberately restricted to DEFINED-RISK strategies
only - every strategy here has a mathematically capped maximum loss,
known at entry. No naked/undefined-risk options are ever proposable by
design (this is enforced by the enum itself, not just a prompt
instruction - the Proposer can only select from these values).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class StrategyType(str, Enum):
    LONG_CALL = "long_call"                # bullish, defined risk = premium paid
    LONG_PUT = "long_put"                  # bearish, defined risk = premium paid
    BULL_CALL_SPREAD = "bull_call_spread"  # bullish debit spread, defined risk = net debit
    BEAR_PUT_SPREAD = "bear_put_spread"    # bearish debit spread, defined risk = net debit
    BULL_PUT_SPREAD = "bull_put_spread"    # bullish credit spread, defined risk = spread width - credit
    BEAR_CALL_SPREAD = "bear_call_spread"  # bearish credit spread, defined risk = spread width - credit


# How many legs each strategy requires - used for validation
STRATEGY_LEG_COUNT = {
    StrategyType.LONG_CALL: 1,
    StrategyType.LONG_PUT: 1,
    StrategyType.BULL_CALL_SPREAD: 2,
    StrategyType.BEAR_PUT_SPREAD: 2,
    StrategyType.BULL_PUT_SPREAD: 2,
    StrategyType.BEAR_CALL_SPREAD: 2,
}


@dataclass
class OptionLeg:
    """One leg of an options position."""
    side: str          # 'buy' | 'sell'
    option_type: str   # 'call' | 'put'
    strike: float
    expiry: str         # ISO date string, e.g. '2026-09-18'
    quantity: int = 1

    def to_dict(self) -> dict:
        return {
            "side": self.side,
            "option_type": self.option_type,
            "strike": self.strike,
            "expiry": self.expiry,
            "quantity": self.quantity,
        }


@dataclass
class Proposal:
    """A trade idea generated by the Proposer, before Critic review."""
    symbol: str
    strategy_type: StrategyType
    timeframe: str
    legs: list[OptionLeg]
    rationale: str
    confidence: float  # 0.0-1.0
    max_loss_estimate: float | None = None  # dollar amount, if computable

    def validate_leg_count(self) -> bool:
        expected = STRATEGY_LEG_COUNT[self.strategy_type]
        return len(self.legs) == expected


@dataclass
class CriticReview:
    """The Critic's independent assessment of a Proposal."""
    verdict: str        # 'approve' | 'reject' | 'flag'
    rationale: str
    risk_score: float   # 0.0 (safest) - 1.0 (riskiest)
    concerns: list[str] | None = None
