-- ============================================================
-- Alpaca Hackathon Bot - Initial Schema
-- Run this in Supabase SQL Editor (Project -> SQL Editor -> New Query)
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- 1. signals
-- Raw indicator snapshots computed by the signal engine.
-- One row per (symbol, timestamp) scan.
-- ------------------------------------------------------------
create table if not exists signals (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    symbol            text not null,
    timeframe         text not null check (timeframe in ('short', 'medium', 'long')),

    -- Indicator values
    iv_rank           numeric,
    iv_percentile     numeric,
    rsi               numeric,
    ma_trend          text,           -- e.g. 'bullish', 'bearish', 'neutral'
    macd              numeric,
    macd_signal       numeric,
    macd_histogram    numeric,
    atr               numeric,
    hv_iv_spread      numeric,
    volume            bigint,
    avg_volume_20d    bigint,
    market_cap        numeric,

    -- Underlying price context at scan time
    underlying_price  numeric,

    raw_data          jsonb           -- full indicator dump for debugging/audit
);

create index if not exists idx_signals_symbol_created on signals (symbol, created_at desc);

-- ------------------------------------------------------------
-- 2. proposals
-- Trade ideas generated by the Proposer agent, after Critic review.
-- ------------------------------------------------------------
create table if not exists proposals (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    signal_id         uuid references signals(id),

    symbol            text not null,
    strategy_type     text not null,   -- e.g. 'long_call', 'put_credit_spread', etc.
    timeframe         text not null check (timeframe in ('short', 'medium', 'long')),

    -- Proposer output
    proposer_rationale     text,
    proposer_confidence    numeric,    -- 0-1
    proposed_contracts     jsonb,      -- option leg details: strike, expiry, side, qty

    -- Critic output
    critic_verdict          text check (critic_verdict in ('approve', 'reject', 'flag')),
    critic_rationale         text,
    critic_risk_score        numeric,  -- 0-1, higher = riskier

    -- Lifecycle
    status            text not null default 'pending_review'
                      check (status in (
                          'pending_review', 'approved', 'rejected',
                          'wishlisted', 'executed', 'expired'
                      )),
    execution_mode_at_creation text,   -- 'manual' or 'auto', for audit trail

    reviewed_at       timestamptz,
    reviewed_by       text            -- 'human' or 'auto_critic'
);

create index if not exists idx_proposals_status on proposals (status);
create index if not exists idx_proposals_symbol on proposals (symbol);

-- ------------------------------------------------------------
-- 3. trades
-- Actual executed orders (post-Alpaca submission).
-- ------------------------------------------------------------
create table if not exists trades (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    proposal_id       uuid references proposals(id),

    alpaca_order_id   text,
    symbol            text not null,
    strategy_type     text,
    contracts         jsonb,          -- executed leg details

    side              text,           -- 'buy' / 'sell'
    quantity          integer,
    fill_price         numeric,
    status            text not null default 'submitted'
                      check (status in (
                          'submitted', 'filled', 'partially_filled',
                          'canceled', 'rejected', 'closed'
                      )),

    opened_at         timestamptz,
    closed_at         timestamptz,
    realized_pnl      numeric,

    raw_order_response jsonb          -- full Alpaca response for debugging
);

create index if not exists idx_trades_status on trades (status);
create index if not exists idx_trades_proposal on trades (proposal_id);

-- ------------------------------------------------------------
-- 4. wishlist
-- Proposals a human liked but didn't execute yet (e.g. waiting for
-- a better entry). Includes a signal snapshot + staleness check so
-- the dashboard can warn if conditions have moved since wishlisting.
-- ------------------------------------------------------------
create table if not exists wishlist (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    proposal_id       uuid references proposals(id),

    symbol            text not null,
    notes             text,

    -- Snapshot of key signal values at the moment of wishlisting,
    -- used to detect staleness later.
    signal_snapshot   jsonb not null,
    snapshot_taken_at timestamptz not null default now(),

    -- Staleness: dashboard/backend computes this by re-checking current
    -- signals against signal_snapshot; this column caches the last check.
    is_stale          boolean default false,
    last_staleness_check_at timestamptz,

    status            text not null default 'active'
                      check (status in ('active', 'promoted', 'discarded'))
);

create index if not exists idx_wishlist_status on wishlist (status);

-- ------------------------------------------------------------
-- 5. reviews_rejections
-- Human (or Critic) review decisions, including rejections with reasons.
-- Kept separate from `proposals` status so we retain full review HISTORY
-- even if a proposal is re-reviewed.
-- ------------------------------------------------------------
create table if not exists reviews_rejections (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    proposal_id       uuid references proposals(id) not null,

    reviewer_type     text not null check (reviewer_type in ('human', 'auto_critic')),
    decision          text not null check (decision in ('approve', 'reject', 'flag', 'wishlist')),
    reason            text,

    -- If rejected, useful for the dashboard/demo to categorize why
    rejection_category text   -- e.g. 'too_risky', 'bad_timing', 'low_confidence', 'other'
);

create index if not exists idx_reviews_proposal on reviews_rejections (proposal_id);

-- ------------------------------------------------------------
-- 6. circuit_breaker_events
-- Full audit log of every circuit breaker check (tripped or not),
-- plus manual halt/resume actions.
-- ------------------------------------------------------------
create table if not exists circuit_breaker_events (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),

    check_point       text not null check (check_point in ('pre_scan', 'pre_execution', 'manual')),
    tripped           boolean not null,
    reasons           jsonb,          -- array of TripReason values

    -- Snapshot at time of check, for audit trail
    equity            numeric,
    last_equity       numeric,
    daily_pnl_pct     numeric,
    open_positions_count integer,
    trades_today_count   integer,

    -- If this event represents a human clearing a sticky pause
    cleared_by_human  boolean default false,
    cleared_at        timestamptz,
    clear_notes       text
);

create index if not exists idx_breaker_events_created on circuit_breaker_events (created_at desc);
create index if not exists idx_breaker_events_tripped on circuit_breaker_events (tripped);

-- ============================================================
-- End of initial schema
-- ============================================================
